"""Generate shim classes for the Minecraft 1.21 classes Voxy needs that 1.20.1 does not have.

The link checker already tells us which classes are unresolved and which members Voxy calls on them.
For each of those classes this writes a Java source under shims/ that declares exactly that surface, so
Voxy's bytecode links on 1.20.1. Bodies are deliberately empty: the port's next milestone is "Voxy
loads", and running the game is what proves which of these calls actually matter.

    make_shims.py <link-report> <out dir>
"""
import re
import sys
from pathlib import Path

JAVA_KEYWORDS = {"abstract", "assert", "boolean", "break", "byte", "case", "catch", "char", "class",
                 "const", "continue", "default", "do", "double", "else", "enum", "extends", "final",
                 "finally", "float", "for", "goto", "if", "implements", "import", "instanceof", "int",
                 "interface", "long", "native", "new", "package", "private", "protected", "public",
                 "return", "short", "static", "strictfp", "super", "switch", "synchronized", "this",
                 "throw", "throws", "transient", "try", "void", "volatile", "while"}

PRIMITIVES = {"V", "Z", "B", "C", "S", "I", "J", "F", "D"}


def java_type(descriptor: str) -> str:
    """JVM descriptor -> Java source type."""
    dims = 0
    while descriptor.startswith("["):
        dims += 1
        descriptor = descriptor[1:]
    if descriptor in PRIMITIVES:
        base = {"V": "void", "Z": "boolean", "B": "byte", "C": "char", "S": "short",
                "I": "int", "J": "long", "F": "float", "D": "double"}[descriptor]
    else:
        base = descriptor.lstrip("L").rstrip(";").replace("/", ".")
    return base + "[]" * dims


def member_name(raw: str) -> str:
    name = raw.split("(")[0]
    return f"`{name}`" if name in JAVA_KEYWORDS else name


NAME_AND_DESCRIPTOR = re.compile(
    r"^([A-Za-z_$][\w$]*?)((?:\[[BCDFIJSZV]|L[\w$/]+;).*$)")


def split_field(entry: str) -> tuple[str, str]:
    """The link checker prints fields as name+descriptor with no separator, so the split has to come
    from the descriptor grammar: the shortest name that leaves a valid descriptor behind."""
    match = NAME_AND_DESCRIPTOR.match(entry)
    if not match:
        return entry, "Ljava/lang/Object;"
    return match.group(1), match.group(2)


def split_parameters(descriptor: str) -> list[str]:
    inner = descriptor[1:descriptor.rindex(")")]
    parameters = []
    index = 0
    while index < len(inner):
        start = index
        while index < len(inner) and inner[index] == "[":
            index += 1
        if index < len(inner) and inner[index] == "L":
            index = inner.index(";", index) + 1
        else:
            index += 1
        parameters.append(inner[start:index])
    return parameters


def main() -> None:
    report = Path(sys.argv[1]).read_text(encoding="utf-8")
    out_dir = Path(sys.argv[2])
    java_dir = out_dir / "src" / "main" / "java" / "net" / "minecraft"
    java_dir.mkdir(parents=True, exist_ok=True)

    classes_section = report.split("--- unresolved classes")[1].split("--- unresolved methods")[0]
    missing = re.findall(r"\s+(\d+)\s+(net/minecraft/class_\d+)", classes_section)
    tail = report.split("--- unresolved methods")[1]
    methods_part, fields_part = tail.split("--- unresolved fields")
    fields_part = fields_part.split("--- unresolved")[0]

    methods_by_owner: dict[str, set[str]] = {}
    for line in methods_part.splitlines():
        if not line.strip():
            continue
        entry = line.split(None, 1)[1].strip()
        owner, _, member = entry.partition(".")
        methods_by_owner.setdefault(owner, set()).add(member)

    fields_by_owner: dict[str, set[str]] = {}
    for line in fields_part.splitlines():
        if not line.strip():
            continue
        entry = line.split(None, 1)[1].strip()
        owner, _, member = entry.partition(".")
        fields_by_owner.setdefault(owner, set()).add(member)

    written = []
    for _, internal in missing:
        class_name = internal.rsplit("/", 1)[-1]
        lines = [
            "package net.minecraft;",
            "",
            "/**",
            f" * RoxyForge shim for {internal}, which exists in Minecraft 1.21 but not in 1.20.1.",
            " *",
            " * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link",
            " * checker found in Voxy. Only the surface Voxy actually touches is declared. Bodies are",
            " * placeholders: this gets Voxy's bytecode to link, and the game run is what shows which",
            " * of these calls need real implementations.",
            " */",
            f"public class {class_name} {{",
        ]
        for member in sorted(fields_by_owner.get(internal, ())):
            name, descriptor = split_field(member)
            lines.append(f"    public {java_type(descriptor)} {member_name(name)};")
        for member in sorted(methods_by_owner.get(internal, ())):
            name = member.split("(")[0]
            descriptor = "(" + member.split("(", 1)[1]
            types = [java_type(part) for part in split_parameters(descriptor)]
            argument_list = ", ".join(f"{type} argument{position}" for position, type in enumerate(types))
            returns = java_type(descriptor[descriptor.rindex(")") + 1:])
            lines.append(f"    public {returns} {member_name(name)}({argument_list}) {{")
            lines.append("        throw new UnsupportedOperationException(\"RoxyForge shim\");")
            lines.append("    }")
        lines.append("}")
        target = java_dir / f"{class_name}.java"
        target.write_text("\n".join(lines) + "\n", encoding="utf-8")
        written.append((internal, len(fields_by_owner.get(internal, ())), len(methods_by_owner.get(internal, ()))))

    for internal, fields, methods in written:
        print(f"{internal:32} fields={fields:<3} methods={methods}")
    print(f"\n{len(written)} shim sources written to {java_dir}")


if __name__ == "__main__":
    main()