package net.rasanovum.roxy.shim;

/**
 * Stands in for net/minecraft/class_11630, which exists in Minecraft 1.21 but not in 1.20.1.
 *
 * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link
 * checker found in Voxy; the mapping points Voxy's calls at this class. Members keep the names
 * Voxy uses, so only the owner is rewritten.
 *
 * Bodies throw on purpose - this milestone is "Voxy links on 1.20.1".
 */
public class Shim11630 {
    public void method_72744(net.minecraft.resources.ResourceLocation argument0, java.util.Collection argument1) {
        throw new UnsupportedOperationException("RoxyForge shim Shim11630.method_72744");
    }
    public void method_72747(java.lang.String argument0) {
        throw new UnsupportedOperationException("RoxyForge shim Shim11630.method_72747");
    }
}
