package net.rasanovum.roxy.shim;

/**
 * Stands in for net/minecraft/class_12253, which exists in Minecraft 1.21 but not in 1.20.1.
 *
 * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link
 * checker found in Voxy; the mapping points Voxy's calls at this class. Members keep the names
 * Voxy uses, so only the owner is rewritten.
 *
 * Bodies throw on purpose - this milestone is "Voxy links on 1.20.1".
 */
public class Shim12253 {
    public net.rasanovum.roxy.shim.Shim12253 field_64080;
}
