package net.rasanovum.roxy.shim;

/**
 * Stands in for net/minecraft/class_11897, which exists in Minecraft 1.21 but not in 1.20.1.
 *
 * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link
 * checker found in Voxy; the mapping points Voxy's calls at this class. Members keep the names
 * Voxy uses, so only the owner is rewritten.
 *
 * Bodies throw on purpose - this milestone is "Voxy links on 1.20.1".
 */
public class Shim11897 {
    public com.mojang.serialization.Codec comp_4787() {
        throw new UnsupportedOperationException("RoxyForge shim Shim11897.comp_4787");
    }
    public com.mojang.serialization.Codec comp_4790() {
        throw new UnsupportedOperationException("RoxyForge shim Shim11897.comp_4790");
    }
    public net.rasanovum.roxy.shim.Shim11897 method_74159(net.minecraft.core.RegistryAccess argument0) {
        throw new UnsupportedOperationException("RoxyForge shim Shim11897.method_74159");
    }
}
