package net.rasanovum.roxy.shim;

/**
 * Stands in for net/minecraft/class_11631, which exists in Minecraft 1.21 but not in 1.20.1.
 *
 * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link
 * checker found in Voxy; the mapping points Voxy's calls at this class. Members keep the names
 * Voxy uses, so only the owner is rewritten.
 *
 * Bodies throw on purpose - this milestone is "Voxy links on 1.20.1".
 */
public class Shim11631 {
    public net.minecraft.resources.ResourceLocation method_72763(net.minecraft.resources.ResourceLocation argument0, net.rasanovum.roxy.shim.Shim11632 argument1) {
        throw new UnsupportedOperationException("RoxyForge shim Shim11631.method_72763");
    }
}
