package net.rasanovum.roxy.bridge;

/**
 * Stands in for the Minecraft calls Voxy makes that Minecraft 1.20.1 cannot satisfy.
 *
 * Generated by tools/roxy-mappings/make_bridges.py from the unresolved references the link
 * checker reported, and wired up by RoxyForgeRemapper: a call to
 * {@code Owner.member(args)} is rewritten into {@code RoxyBridge.mNNNN(owner, args)}.
 *
 * Every body throws on purpose. This milestone is "Voxy links on 1.20.1"; implementing the
 * bodies against the 1.20.1 API is the next one, and the game run is what shows which of these
 * calls Voxy actually needs at runtime.
 */
public final class RoxyBridge {
    private RoxyBridge() {
    }

    /** Voxy calls net/minecraft/client/OptionInstance.m_231547_()Ljava/lang/Object;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.OptionInstance, returns java.lang.Object. */
    public static Object m0001(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0001: net/minecraft/client/OptionInstance.m_231547_");
    }
    // TODO: implement m0001 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/model/geom/ModelPart.method_68509(Lnet/minecraft/core/Direction;)Ljava/util/List;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.model.geom.ModelPart, returns java.util.List. */
    public static Object m0002(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0002: net/minecraft/client/model/geom/ModelPart.method_68509");
    }
    // TODO: implement m0002 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/ClientChunkCache$Storage.m_104481_(I)Lnet/minecraft/world/level/chunk/LevelChunk;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.multiplayer.ClientChunkCache$Storage, returns net.minecraft.world.level.chunk.LevelChunk. */
    public static Object m0003(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0003: net/minecraft/client/multiplayer/ClientChunkCache$Storage.m_104481_");
    }
    // TODO: implement m0003 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/ClientChunkCache.m_104448_(IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Lnet/minecraft/world/level/chunk/LevelChunk;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.multiplayer.ClientChunkCache, returns net.minecraft.world.level.chunk.LevelChunk. */
    public static Object m0004(Object self, Object argument0, Object argument1, Object argument2, Object argument3) {
        throw new UnsupportedOperationException("RoxyForge bridge m0004: net/minecraft/client/multiplayer/ClientChunkCache.m_104448_");
    }
    // TODO: implement m0004 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/chat/ChatListener.m_240688_(Lnet/minecraft/network/chat/Component;Z)V, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.multiplayer.chat.ChatListener, returns void. */
    public static Object m0005(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0005: net/minecraft/client/multiplayer/chat/ChatListener.m_240688_");
    }
    // TODO: implement m0005 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/GameRenderer.m_253088_(F)Lorg/joml/Matrix4f;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.GameRenderer, returns org.joml.Matrix4f. */
    public static Object m0006(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0006: net/minecraft/client/renderer/GameRenderer.m_253088_");
    }
    // TODO: implement m0006 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/ItemBlockRenderTypes.method_23679(Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.ItemBlockRenderTypes, returns net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0007(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0007: net/minecraft/client/renderer/ItemBlockRenderTypes.method_23679");
    }
    // TODO: implement m0007 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/ItemBlockRenderTypes.method_23680(Lnet/minecraft/world/level/material/FluidState;)Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.ItemBlockRenderTypes, returns net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0008(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0008: net/minecraft/client/renderer/ItemBlockRenderTypes.method_23680");
    }
    // TODO: implement m0008 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/LightTexture.m_109880_()Lcom/mojang/blaze3d/textures/GpuTextureView;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.LightTexture, returns com.mojang.blaze3d.textures.GpuTextureView. */
    public static Object m0009(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0009: net/minecraft/client/renderer/LightTexture.m_109880_");
    }
    // TODO: implement m0009 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/BlockRenderDispatcher.m_110912_(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/VertexConsumer;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/material/FluidState;)V, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.block.BlockRenderDispatcher, returns void. */
    public static Object m0010(Object self, Object argument0, Object argument1, Object argument2, Object argument3, Object argument4) {
        throw new UnsupportedOperationException("RoxyForge bridge m0010: net/minecraft/client/renderer/block/BlockRenderDispatcher.m_110912_");
    }
    // TODO: implement m0010 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/model/BakedQuad.method_76648(I)Lorg/joml/Vector3fc;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.block.model.BakedQuad, returns org.joml.Vector3fc. */
    public static Object m0011(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0011: net/minecraft/client/renderer/block/model/BakedQuad.method_76648");
    }
    // TODO: implement m0011 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/model/BakedQuad.method_76649(I)J, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.block.model.BakedQuad, returns long. */
    public static Object m0012(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0012: net/minecraft/client/renderer/block/model/BakedQuad.method_76649");
    }
    // TODO: implement m0012 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/texture/AbstractTexture.method_68004()Lcom/mojang/blaze3d/textures/GpuTexture;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.texture.AbstractTexture, returns com.mojang.blaze3d.textures.GpuTexture. */
    public static Object m0013(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0013: net/minecraft/client/renderer/texture/AbstractTexture.method_68004");
    }
    // TODO: implement m0013 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/texture/TextureManager.method_4619(Lnet/minecraft/resources/ResourceLocation;)Lnet/minecraft/client/renderer/texture/AbstractTexture;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.renderer.texture.TextureManager, returns net.minecraft.client.renderer.texture.AbstractTexture. */
    public static Object m0014(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0014: net/minecraft/client/renderer/texture/TextureManager.method_4619");
    }
    // TODO: implement m0014 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/resources/model/BakedModel.method_68512(Lnet/minecraft/util/RandomSource;)Ljava/util/List;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.resources.model.BakedModel, returns java.util.List. */
    public static Object m0015(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0015: net/minecraft/client/resources/model/BakedModel.method_68512");
    }
    // TODO: implement m0015 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/resources/model/ModelManager.method_4743()Lnet/minecraft/client/renderer/block/BlockModelShaper;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.resources.model.ModelManager, returns net.minecraft.client.renderer.block.BlockModelShaper. */
    public static Object m0016(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0016: net/minecraft/client/resources/model/ModelManager.method_4743");
    }
    // TODO: implement m0016 against the 1.20.1 API
    /** Voxy calls net/minecraft/client/server/IntegratedServer.method_27050(Lnet/minecraft/world/level/storage/LevelResource;)Ljava/nio/file/Path;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.client.server.IntegratedServer, returns java.nio.file.Path. */
    public static Object m0017(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0017: net/minecraft/client/server/IntegratedServer.method_27050");
    }
    // TODO: implement m0017 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10260()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.BlockPos, returns int. */
    public static Object m0018(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0018: net/minecraft/core/BlockPos.method_10260");
    }
    // TODO: implement m0018 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10263()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.BlockPos, returns int. */
    public static Object m0019(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0019: net/minecraft/core/BlockPos.method_10263");
    }
    // TODO: implement m0019 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10264()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.BlockPos, returns int. */
    public static Object m0020(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0020: net/minecraft/core/BlockPos.method_10264");
    }
    // TODO: implement m0020 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/DefaultedRegistry.method_10206(Ljava/lang/Object;)I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.DefaultedRegistry, returns int. */
    public static Object m0021(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0021: net/minecraft/core/DefaultedRegistry.method_10206");
    }
    // TODO: implement m0021 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.m_235666_(I)Lnet/minecraft/core/Direction;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Direction, returns net.minecraft.core.Direction. */
    public static Object m0022(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0022: net/minecraft/core/Direction.m_235666_");
    }
    // TODO: implement m0022 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.method_62675()Lnet/minecraft/core/Vec3i;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Direction, returns net.minecraft.core.Vec3i. */
    public static Object m0023(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0023: net/minecraft/core/Direction.method_62675");
    }
    // TODO: implement m0023 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.ordinal()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Direction, returns int. */
    public static Object m0024(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0024: net/minecraft/core/Direction.ordinal");
    }
    // TODO: implement m0024 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Holder$Reference.comp_349()Ljava/lang/Object;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Holder$Reference, returns java.lang.Object. */
    public static Object m0025(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0025: net/minecraft/core/Holder$Reference.comp_349");
    }
    // TODO: implement m0025 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/IdMapper.method_10200(I)Ljava/lang/Object;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.IdMapper, returns java.lang.Object. */
    public static Object m0026(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0026: net/minecraft/core/IdMapper.method_10200");
    }
    // TODO: implement m0026 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/IdMapper.method_10204()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.IdMapper, returns int. */
    public static Object m0027(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0027: net/minecraft/core/IdMapper.method_10204");
    }
    // TODO: implement m0027 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_10223(Lnet/minecraft/resources/ResourceLocation;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Registry, returns java.util.Optional. */
    public static Object m0028(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0028: net/minecraft/core/Registry.method_10223");
    }
    // TODO: implement m0028 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_29107(Lnet/minecraft/resources/ResourceKey;)Ljava/lang/Object;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Registry, returns java.lang.Object. */
    public static Object m0029(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0029: net/minecraft/core/Registry.method_29107");
    }
    // TODO: implement m0029 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_46747(Lnet/minecraft/resources/ResourceKey;)Lnet/minecraft/core/Holder$Reference;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.Registry, returns net.minecraft.core.Holder$Reference. */
    public static Object m0030(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0030: net/minecraft/core/Registry.method_46747");
    }
    // TODO: implement m0030 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/RegistryAccess.method_30530(Lnet/minecraft/resources/ResourceKey;)Lnet/minecraft/core/Registry;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.RegistryAccess, returns net.minecraft.core.Registry. */
    public static Object m0031(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0031: net/minecraft/core/RegistryAccess.method_30530");
    }
    // TODO: implement m0031 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/SectionPos.m_123170_(Lnet/minecraft/world/level/ChunkPos;I)Lnet/minecraft/core/SectionPos;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.SectionPos, returns net.minecraft.core.SectionPos. */
    public static Object m0032(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0032: net/minecraft/core/SectionPos.m_123170_");
    }
    // TODO: implement m0032 against the 1.20.1 API
    /** Voxy calls net/minecraft/core/SectionPos.method_18687()I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.core.SectionPos, returns int. */
    public static Object m0033(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0033: net/minecraft/core/SectionPos.method_18687");
    }
    // TODO: implement m0033 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128403_(Ljava/lang/String;I)I, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.CompoundTag, returns int. */
    public static Object m0034(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0034: net/minecraft/nbt/CompoundTag.m_128403_");
    }
    // TODO: implement m0034 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128463_(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0035(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0035: net/minecraft/nbt/CompoundTag.m_128463_");
    }
    // TODO: implement m0035 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128469_(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0036(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0036: net/minecraft/nbt/CompoundTag.m_128469_");
    }
    // TODO: implement m0036 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_274048_(Ljava/lang/String;Lnet/minecraft/nbt/Tag;)Lnet/minecraft/nbt/Tag;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.CompoundTag, returns net.minecraft.nbt.Tag. */
    public static Object m0037(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0037: net/minecraft/nbt/CompoundTag.m_274048_");
    }
    // TODO: implement m0037 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.method_10554(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0038(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0038: net/minecraft/nbt/CompoundTag.method_10554");
    }
    // TODO: implement m0038 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/ListTag.iterator()Ljava/util/Iterator;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.ListTag, returns java.util.Iterator. */
    public static Object m0039(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0039: net/minecraft/nbt/ListTag.iterator");
    }
    // TODO: implement m0039 against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/NbtAccounter.method_53898()Lnet/minecraft/nbt/NbtAccounter;, which 1.20.1 does not have.
     *  Types: owner net.minecraft.nbt.NbtAccounter, returns net.minecraft.nbt.NbtAccounter. */
    public static Object m0040(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0040: net/minecraft/nbt/NbtAccounter.method_53898");
    }
    // TODO: implement m0040 against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0041(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0041: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    public static void m0041Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0041 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    // TODO: implement the m0041 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0042(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0042: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    public static void m0042Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0042 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    // TODO: implement the m0042 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0043(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0043: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    public static void m0043Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0043 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    // TODO: implement the m0043 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0044(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0044: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    public static void m0044Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0044 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;");
    }
    // TODO: implement the m0044 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/block/RenderShape.field_11455Lnet/minecraft/world/level/block/RenderShape; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0045(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0045: net/minecraft/world/level/block/RenderShape.field_11455Lnet/minecraft/world/level/block/RenderShape;");
    }
    public static void m0045Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0045 (set): net/minecraft/world/level/block/RenderShape.field_11455Lnet/minecraft/world/level/block/RenderShape;");
    }
    // TODO: implement the m0045 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/ChunkStatus.field_12798Lnet/minecraft/world/level/chunk/ChunkStatus; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0046(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0046: net/minecraft/world/level/chunk/ChunkStatus.field_12798Lnet/minecraft/world/level/chunk/ChunkStatus;");
    }
    public static void m0046Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0046 (set): net/minecraft/world/level/chunk/ChunkStatus.field_12798Lnet/minecraft/world/level/chunk/ChunkStatus;");
    }
    // TODO: implement the m0046 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/ChunkStatus.field_12803Lnet/minecraft/world/level/chunk/ChunkStatus; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0047(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0047: net/minecraft/world/level/chunk/ChunkStatus.field_12803Lnet/minecraft/world/level/chunk/ChunkStatus;");
    }
    public static void m0047Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0047 (set): net/minecraft/world/level/chunk/ChunkStatus.field_12803Lnet/minecraft/world/level/chunk/ChunkStatus;");
    }
    // TODO: implement the m0047 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118Lnet/minecraft/util/BitStorage; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0048(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0048: net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118Lnet/minecraft/util/BitStorage;");
    }
    public static void m0048Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0048 (set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118Lnet/minecraft/util/BitStorage;");
    }
    // TODO: implement the m0048 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119Lnet/minecraft/world/level/chunk/Palette; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0049(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0049: net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119Lnet/minecraft/world/level/chunk/Palette;");
    }
    public static void m0049Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0049 (set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119Lnet/minecraft/world/level/chunk/Palette;");
    }
    // TODO: implement the m0049 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer.field_34560Lnet/minecraft/world/level/chunk/PalettedContainer$Data; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0050(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0050: net/minecraft/world/level/chunk/PalettedContainer.field_34560Lnet/minecraft/world/level/chunk/PalettedContainer$Data;");
    }
    public static void m0050Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0050 (set): net/minecraft/world/level/chunk/PalettedContainer.field_34560Lnet/minecraft/world/level/chunk/PalettedContainer$Data;");
    }
    // TODO: implement the m0050 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726Lnet/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType; (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0051(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0051: net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726Lnet/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType;");
    }
    public static void m0051Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0051 (set): net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726Lnet/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType;");
    }
    // TODO: implement the m0051 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1350D (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0052(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0052: net/minecraft/world/phys/Vec3.field_1350D");
    }
    public static void m0052Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0052 (set): net/minecraft/world/phys/Vec3.field_1350D");
    }
    // TODO: implement the m0052 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1351D (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0053(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0053: net/minecraft/world/phys/Vec3.field_1351D");
    }
    public static void m0053Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0053 (set): net/minecraft/world/phys/Vec3.field_1351D");
    }
    // TODO: implement the m0053 getter and setter against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1352D (Ljava/lang/Object;), which 1.20.1 does not have.
     *  Type: java.lang.Object. */
    public static Object m0054(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0054: net/minecraft/world/phys/Vec3.field_1352D");
    }
    public static void m0054Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0054 (set): net/minecraft/world/phys/Vec3.field_1352D");
    }
    // TODO: implement the m0054 getter and setter against the 1.20.1 API
}
