package net.rasanovum.roxy.bridge;

/**
 * Stands in for the Minecraft calls Voxy makes that Minecraft 1.20.1 cannot satisfy.
 *
 * Generated by tools/roxy-mappings/make_bridges.py from the unresolved references the link
 * checker reported, and wired up by RoxyForgeRemapper: a call to
 * {@code Owner.member(args)} is rewritten into {@code RoxyBridge.mNNNN(owner, args)}.
 *
 * Every body throws on purpose. This milestone is "Voxy links on 1.20.1"; implementing the
 * bodies against the 1.20.1 API is the next one, and the game run is what shows which of these
 * calls Voxy actually needs at runtime.
 */
public final class RoxyBridge {
    private RoxyBridge() {
    }

    /** Voxy calls net/minecraft/client/OptionInstance.m_231547_()Ljava/lang/Object;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.OptionInstance, returns java.lang.Object. */
    public static Object m0001(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0001: net/minecraft/client/OptionInstance.m_231547_");
    }
    public static Object m0001Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0001 (static): net/minecraft/client/OptionInstance.m_231547_");
    }
    // TODO: implement m0001 and m0001Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/model/geom/ModelPart.method_68509(Lnet/minecraft/core/Direction;)Ljava/util/List;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.model.geom.ModelPart, returns java.util.List. */
    public static Object m0002(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0002: net/minecraft/client/model/geom/ModelPart.method_68509");
    }
    public static Object m0002Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0002 (static): net/minecraft/client/model/geom/ModelPart.method_68509");
    }
    // TODO: implement m0002 and m0002Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/ClientChunkCache$Storage.m_104481_(I)Lnet/minecraft/world/level/chunk/LevelChunk;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.multiplayer.ClientChunkCache$Storage, returns net.minecraft.world.level.chunk.LevelChunk. */
    public static Object m0003(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0003: net/minecraft/client/multiplayer/ClientChunkCache$Storage.m_104481_");
    }
    public static Object m0003Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0003 (static): net/minecraft/client/multiplayer/ClientChunkCache$Storage.m_104481_");
    }
    // TODO: implement m0003 and m0003Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/ClientChunkCache.m_104448_(IILnet/minecraft/world/level/chunk/ChunkStatus;Z)Lnet/minecraft/world/level/chunk/LevelChunk;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.multiplayer.ClientChunkCache, returns net.minecraft.world.level.chunk.LevelChunk. */
    public static Object m0004(Object self, Object argument0, Object argument1, Object argument2, Object argument3) {
        throw new UnsupportedOperationException("RoxyForge bridge m0004: net/minecraft/client/multiplayer/ClientChunkCache.m_104448_");
    }
    public static Object m0004Static(Object argument0, Object argument1, Object argument2, Object argument3) {
        throw new UnsupportedOperationException("RoxyForge bridge m0004 (static): net/minecraft/client/multiplayer/ClientChunkCache.m_104448_");
    }
    // TODO: implement m0004 and m0004Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/multiplayer/chat/ChatListener.m_240688_(Lnet/minecraft/network/chat/Component;Z)V, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.multiplayer.chat.ChatListener, returns void. */
    public static Object m0005(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0005: net/minecraft/client/multiplayer/chat/ChatListener.m_240688_");
    }
    public static Object m0005Static(Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0005 (static): net/minecraft/client/multiplayer/chat/ChatListener.m_240688_");
    }
    // TODO: implement m0005 and m0005Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/GameRenderer.m_253088_(F)Lorg/joml/Matrix4f;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.GameRenderer, returns org.joml.Matrix4f. */
    public static Object m0006(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0006: net/minecraft/client/renderer/GameRenderer.m_253088_");
    }
    public static Object m0006Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0006 (static): net/minecraft/client/renderer/GameRenderer.m_253088_");
    }
    // TODO: implement m0006 and m0006Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/ItemBlockRenderTypes.method_23679(Lnet/minecraft/world/level/block/state/BlockState;)Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.ItemBlockRenderTypes, returns net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0007(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0007: net/minecraft/client/renderer/ItemBlockRenderTypes.method_23679");
    }
    public static Object m0007Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0007 (static): net/minecraft/client/renderer/ItemBlockRenderTypes.method_23679");
    }
    // TODO: implement m0007 and m0007Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/ItemBlockRenderTypes.method_23680(Lnet/minecraft/world/level/material/FluidState;)Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.ItemBlockRenderTypes, returns net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0008(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0008: net/minecraft/client/renderer/ItemBlockRenderTypes.method_23680");
    }
    public static Object m0008Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0008 (static): net/minecraft/client/renderer/ItemBlockRenderTypes.method_23680");
    }
    // TODO: implement m0008 and m0008Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/LightTexture.m_109880_()Lcom/mojang/blaze3d/textures/GpuTextureView;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.LightTexture, returns com.mojang.blaze3d.textures.GpuTextureView. */
    public static Object m0009(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0009: net/minecraft/client/renderer/LightTexture.m_109880_");
    }
    public static Object m0009Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0009 (static): net/minecraft/client/renderer/LightTexture.m_109880_");
    }
    // TODO: implement m0009 and m0009Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/BlockRenderDispatcher.m_110912_(Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/BlockAndTintGetter;Lcom/mojang/blaze3d/vertex/VertexConsumer;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/level/material/FluidState;)V, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.block.BlockRenderDispatcher, returns void. */
    public static Object m0010(Object self, Object argument0, Object argument1, Object argument2, Object argument3, Object argument4) {
        throw new UnsupportedOperationException("RoxyForge bridge m0010: net/minecraft/client/renderer/block/BlockRenderDispatcher.m_110912_");
    }
    public static Object m0010Static(Object argument0, Object argument1, Object argument2, Object argument3, Object argument4) {
        throw new UnsupportedOperationException("RoxyForge bridge m0010 (static): net/minecraft/client/renderer/block/BlockRenderDispatcher.m_110912_");
    }
    // TODO: implement m0010 and m0010Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/model/BakedQuad.method_76648(I)Lorg/joml/Vector3fc;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.block.model.BakedQuad, returns org.joml.Vector3fc. */
    public static Object m0011(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0011: net/minecraft/client/renderer/block/model/BakedQuad.method_76648");
    }
    public static Object m0011Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0011 (static): net/minecraft/client/renderer/block/model/BakedQuad.method_76648");
    }
    // TODO: implement m0011 and m0011Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/block/model/BakedQuad.method_76649(I)J, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.block.model.BakedQuad, returns long. */
    public static Object m0012(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0012: net/minecraft/client/renderer/block/model/BakedQuad.method_76649");
    }
    public static Object m0012Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0012 (static): net/minecraft/client/renderer/block/model/BakedQuad.method_76649");
    }
    // TODO: implement m0012 and m0012Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/texture/AbstractTexture.method_68004()Lcom/mojang/blaze3d/textures/GpuTexture;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.texture.AbstractTexture, returns com.mojang.blaze3d.textures.GpuTexture. */
    public static Object m0013(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0013: net/minecraft/client/renderer/texture/AbstractTexture.method_68004");
    }
    public static Object m0013Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0013 (static): net/minecraft/client/renderer/texture/AbstractTexture.method_68004");
    }
    // TODO: implement m0013 and m0013Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/renderer/texture/TextureManager.method_4619(Lnet/minecraft/resources/ResourceLocation;)Lnet/minecraft/client/renderer/texture/AbstractTexture;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.renderer.texture.TextureManager, returns net.minecraft.client.renderer.texture.AbstractTexture. */
    public static Object m0014(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0014: net/minecraft/client/renderer/texture/TextureManager.method_4619");
    }
    public static Object m0014Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0014 (static): net/minecraft/client/renderer/texture/TextureManager.method_4619");
    }
    // TODO: implement m0014 and m0014Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/resources/model/BakedModel.method_68512(Lnet/minecraft/util/RandomSource;)Ljava/util/List;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.resources.model.BakedModel, returns java.util.List. */
    public static Object m0015(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0015: net/minecraft/client/resources/model/BakedModel.method_68512");
    }
    public static Object m0015Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0015 (static): net/minecraft/client/resources/model/BakedModel.method_68512");
    }
    // TODO: implement m0015 and m0015Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/resources/model/ModelManager.method_4743()Lnet/minecraft/client/renderer/block/BlockModelShaper;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.resources.model.ModelManager, returns net.minecraft.client.renderer.block.BlockModelShaper. */
    public static Object m0016(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0016: net/minecraft/client/resources/model/ModelManager.method_4743");
    }
    public static Object m0016Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0016 (static): net/minecraft/client/resources/model/ModelManager.method_4743");
    }
    // TODO: implement m0016 and m0016Static against the 1.20.1 API
    /** Voxy calls net/minecraft/client/server/IntegratedServer.method_27050(Lnet/minecraft/world/level/storage/LevelResource;)Ljava/nio/file/Path;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.client.server.IntegratedServer, returns java.nio.file.Path. */
    public static Object m0017(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0017: net/minecraft/client/server/IntegratedServer.method_27050");
    }
    public static Object m0017Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0017 (static): net/minecraft/client/server/IntegratedServer.method_27050");
    }
    // TODO: implement m0017 and m0017Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10260()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.BlockPos, returns int. */
    public static Object m0018(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0018: net/minecraft/core/BlockPos.method_10260");
    }
    public static Object m0018Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0018 (static): net/minecraft/core/BlockPos.method_10260");
    }
    // TODO: implement m0018 and m0018Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10263()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.BlockPos, returns int. */
    public static Object m0019(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0019: net/minecraft/core/BlockPos.method_10263");
    }
    public static Object m0019Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0019 (static): net/minecraft/core/BlockPos.method_10263");
    }
    // TODO: implement m0019 and m0019Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/BlockPos.method_10264()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.BlockPos, returns int. */
    public static Object m0020(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0020: net/minecraft/core/BlockPos.method_10264");
    }
    public static Object m0020Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0020 (static): net/minecraft/core/BlockPos.method_10264");
    }
    // TODO: implement m0020 and m0020Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/DefaultedRegistry.method_10206(Ljava/lang/Object;)I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.DefaultedRegistry, returns int. */
    public static Object m0021(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0021: net/minecraft/core/DefaultedRegistry.method_10206");
    }
    public static Object m0021Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0021 (static): net/minecraft/core/DefaultedRegistry.method_10206");
    }
    // TODO: implement m0021 and m0021Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.m_235666_(I)Lnet/minecraft/core/Direction;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Direction, returns net.minecraft.core.Direction. */
    public static Object m0022(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0022: net/minecraft/core/Direction.m_235666_");
    }
    public static Object m0022Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0022 (static): net/minecraft/core/Direction.m_235666_");
    }
    // TODO: implement m0022 and m0022Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.method_62675()Lnet/minecraft/core/Vec3i;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Direction, returns net.minecraft.core.Vec3i. */
    public static Object m0023(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0023: net/minecraft/core/Direction.method_62675");
    }
    public static Object m0023Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0023 (static): net/minecraft/core/Direction.method_62675");
    }
    // TODO: implement m0023 and m0023Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Direction.ordinal()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Direction, returns int. */
    public static Object m0024(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0024: net/minecraft/core/Direction.ordinal");
    }
    public static Object m0024Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0024 (static): net/minecraft/core/Direction.ordinal");
    }
    // TODO: implement m0024 and m0024Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Holder$Reference.comp_349()Ljava/lang/Object;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Holder$Reference, returns java.lang.Object. */
    public static Object m0025(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0025: net/minecraft/core/Holder$Reference.comp_349");
    }
    public static Object m0025Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0025 (static): net/minecraft/core/Holder$Reference.comp_349");
    }
    // TODO: implement m0025 and m0025Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/IdMapper.method_10200(I)Ljava/lang/Object;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.IdMapper, returns java.lang.Object. */
    public static Object m0026(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0026: net/minecraft/core/IdMapper.method_10200");
    }
    public static Object m0026Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0026 (static): net/minecraft/core/IdMapper.method_10200");
    }
    // TODO: implement m0026 and m0026Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/IdMapper.method_10204()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.IdMapper, returns int. */
    public static Object m0027(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0027: net/minecraft/core/IdMapper.method_10204");
    }
    public static Object m0027Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0027 (static): net/minecraft/core/IdMapper.method_10204");
    }
    // TODO: implement m0027 and m0027Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_10223(Lnet/minecraft/resources/ResourceLocation;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Registry, returns java.util.Optional. */
    public static Object m0028(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0028: net/minecraft/core/Registry.method_10223");
    }
    public static Object m0028Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0028 (static): net/minecraft/core/Registry.method_10223");
    }
    // TODO: implement m0028 and m0028Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_29107(Lnet/minecraft/resources/ResourceKey;)Ljava/lang/Object;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Registry, returns java.lang.Object. */
    public static Object m0029(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0029: net/minecraft/core/Registry.method_29107");
    }
    public static Object m0029Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0029 (static): net/minecraft/core/Registry.method_29107");
    }
    // TODO: implement m0029 and m0029Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/Registry.method_46747(Lnet/minecraft/resources/ResourceKey;)Lnet/minecraft/core/Holder$Reference;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.Registry, returns net.minecraft.core.Holder$Reference. */
    public static Object m0030(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0030: net/minecraft/core/Registry.method_46747");
    }
    public static Object m0030Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0030 (static): net/minecraft/core/Registry.method_46747");
    }
    // TODO: implement m0030 and m0030Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/RegistryAccess.method_30530(Lnet/minecraft/resources/ResourceKey;)Lnet/minecraft/core/Registry;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.RegistryAccess, returns net.minecraft.core.Registry. */
    public static Object m0031(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0031: net/minecraft/core/RegistryAccess.method_30530");
    }
    public static Object m0031Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0031 (static): net/minecraft/core/RegistryAccess.method_30530");
    }
    // TODO: implement m0031 and m0031Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/SectionPos.m_123170_(Lnet/minecraft/world/level/ChunkPos;I)Lnet/minecraft/core/SectionPos;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.SectionPos, returns net.minecraft.core.SectionPos. */
    public static Object m0032(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0032: net/minecraft/core/SectionPos.m_123170_");
    }
    public static Object m0032Static(Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0032 (static): net/minecraft/core/SectionPos.m_123170_");
    }
    // TODO: implement m0032 and m0032Static against the 1.20.1 API
    /** Voxy calls net/minecraft/core/SectionPos.method_18687()I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.core.SectionPos, returns int. */
    public static Object m0033(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0033: net/minecraft/core/SectionPos.method_18687");
    }
    public static Object m0033Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0033 (static): net/minecraft/core/SectionPos.method_18687");
    }
    // TODO: implement m0033 and m0033Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128403_(Ljava/lang/String;I)I, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.CompoundTag, returns int. */
    public static Object m0034(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0034: net/minecraft/nbt/CompoundTag.m_128403_");
    }
    public static Object m0034Static(Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0034 (static): net/minecraft/nbt/CompoundTag.m_128403_");
    }
    // TODO: implement m0034 and m0034Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128463_(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0035(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0035: net/minecraft/nbt/CompoundTag.m_128463_");
    }
    public static Object m0035Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0035 (static): net/minecraft/nbt/CompoundTag.m_128463_");
    }
    // TODO: implement m0035 and m0035Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_128469_(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0036(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0036: net/minecraft/nbt/CompoundTag.m_128469_");
    }
    public static Object m0036Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0036 (static): net/minecraft/nbt/CompoundTag.m_128469_");
    }
    // TODO: implement m0036 and m0036Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.m_274048_(Ljava/lang/String;Lnet/minecraft/nbt/Tag;)Lnet/minecraft/nbt/Tag;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.CompoundTag, returns net.minecraft.nbt.Tag. */
    public static Object m0037(Object self, Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0037: net/minecraft/nbt/CompoundTag.m_274048_");
    }
    public static Object m0037Static(Object argument0, Object argument1) {
        throw new UnsupportedOperationException("RoxyForge bridge m0037 (static): net/minecraft/nbt/CompoundTag.m_274048_");
    }
    // TODO: implement m0037 and m0037Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/CompoundTag.method_10554(Ljava/lang/String;)Ljava/util/Optional;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.CompoundTag, returns java.util.Optional. */
    public static Object m0038(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0038: net/minecraft/nbt/CompoundTag.method_10554");
    }
    public static Object m0038Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0038 (static): net/minecraft/nbt/CompoundTag.method_10554");
    }
    // TODO: implement m0038 and m0038Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/ListTag.iterator()Ljava/util/Iterator;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.ListTag, returns java.util.Iterator. */
    public static Object m0039(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0039: net/minecraft/nbt/ListTag.iterator");
    }
    public static Object m0039Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0039 (static): net/minecraft/nbt/ListTag.iterator");
    }
    // TODO: implement m0039 and m0039Static against the 1.20.1 API
    /** Voxy calls net/minecraft/nbt/NbtAccounter.method_53898()Lnet/minecraft/nbt/NbtAccounter;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.nbt.NbtAccounter, returns net.minecraft.nbt.NbtAccounter. */
    public static Object m0040(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0040: net/minecraft/nbt/NbtAccounter.method_53898");
    }
    public static Object m0040Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0040 (static): net/minecraft/nbt/NbtAccounter.method_53898");
    }
    // TODO: implement m0040 and m0040Static against the 1.20.1 API
    /** Voxy calls net/minecraft/network/chat/Component.m_130668_(Ljava/lang/String;)Lnet/minecraft/network/chat/Component;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.network.chat.Component, returns net.minecraft.network.chat.Component. */
    public static Object m0041(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0041: net/minecraft/network/chat/Component.m_130668_");
    }
    public static Object m0041Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0041 (static): net/minecraft/network/chat/Component.m_130668_");
    }
    // TODO: implement m0041 and m0041Static against the 1.20.1 API
    /** Voxy calls net/minecraft/network/chat/Component.m_237099_(Ljava/lang/String;)Lnet/minecraft/network/chat/MutableComponent;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.network.chat.Component, returns net.minecraft.network.chat.MutableComponent. */
    public static Object m0042(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0042: net/minecraft/network/chat/Component.m_237099_");
    }
    public static Object m0042Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0042 (static): net/minecraft/network/chat/Component.m_237099_");
    }
    // TODO: implement m0042 and m0042Static against the 1.20.1 API
    /** Voxy calls net/minecraft/resources/ResourceLocation.method_60654(Ljava/lang/String;)Lnet/minecraft/resources/ResourceLocation;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.resources.ResourceLocation, returns net.minecraft.resources.ResourceLocation. */
    public static Object m0043(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0043: net/minecraft/resources/ResourceLocation.method_60654");
    }
    public static Object m0043Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0043 (static): net/minecraft/resources/ResourceLocation.method_60654");
    }
    // TODO: implement m0043 and m0043Static against the 1.20.1 API
    /** Voxy calls net/minecraft/world/level/block/Block.m_49965_()Lnet/minecraft/world/level/block/state/BlockState;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.world.level.block.Block, returns net.minecraft.world.level.block.state.BlockState. */
    public static Object m0044(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0044: net/minecraft/world/level/block/Block.m_49965_");
    }
    public static Object m0044Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0044 (static): net/minecraft/world/level/block/Block.m_49965_");
    }
    // TODO: implement m0044 and m0044Static against the 1.20.1 API
    /** Voxy calls net/minecraft/world/level/chunk/DataLayer.m_156341_()Lnet/minecraft/world/level/chunk/DataLayer;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.world.level.chunk.DataLayer, returns net.minecraft.world.level.chunk.DataLayer. */
    public static Object m0045(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0045: net/minecraft/world/level/chunk/DataLayer.m_156341_");
    }
    public static Object m0045Static() {
        throw new UnsupportedOperationException("RoxyForge bridge m0045 (static): net/minecraft/world/level/chunk/DataLayer.m_156341_");
    }
    // TODO: implement m0045 and m0045Static against the 1.20.1 API
    /** Voxy calls net/minecraft/world/level/chunk/storage/RegionFileVersion.m_63755_(I)Lnet/minecraft/world/level/chunk/storage/RegionFileVersion;, which 1.20.1 does not have.
     *  Owner type: net.minecraft.world.level.chunk.storage.RegionFileVersion, returns net.minecraft.world.level.chunk.storage.RegionFileVersion. */
    public static Object m0046(Object self, Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0046: net/minecraft/world/level/chunk/storage/RegionFileVersion.m_63755_");
    }
    public static Object m0046Static(Object argument0) {
        throw new UnsupportedOperationException("RoxyForge bridge m0046 (static): net/minecraft/world/level/chunk/storage/RegionFileVersion.m_63755_");
    }
    // TODO: implement m0046 and m0046Static against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923 (Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;), which 1.20.1 does not have.
     *  Type: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0047(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0047: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923");
    }
    public static void m0047Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0047 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923");
    }
    public static Object m0047StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0047 (static get): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923");
    }
    public static void m0047StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0047 (static set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60923");
    }
    // TODO: implement the m0047 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925 (Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;), which 1.20.1 does not have.
     *  Type: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0048(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0048: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925");
    }
    public static void m0048Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0048 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925");
    }
    public static Object m0048StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0048 (static get): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925");
    }
    public static void m0048StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0048 (static set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60925");
    }
    // TODO: implement the m0048 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926 (Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;), which 1.20.1 does not have.
     *  Type: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0049(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0049: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926");
    }
    public static void m0049Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0049 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926");
    }
    public static Object m0049StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0049 (static get): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926");
    }
    public static void m0049StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0049 (static set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60926");
    }
    // TODO: implement the m0049 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927 (Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;), which 1.20.1 does not have.
     *  Type: net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$RenderChunk. */
    public static Object m0050(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0050: net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927");
    }
    public static void m0050Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0050 (set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927");
    }
    public static Object m0050StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0050 (static get): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927");
    }
    public static void m0050StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0050 (static set): net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk.field_60927");
    }
    // TODO: implement the m0050 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/block/RenderShape.field_11455 (Lnet/minecraft/world/level/block/RenderShape;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.block.RenderShape. */
    public static Object m0051(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0051: net/minecraft/world/level/block/RenderShape.field_11455");
    }
    public static void m0051Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0051 (set): net/minecraft/world/level/block/RenderShape.field_11455");
    }
    public static Object m0051StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0051 (static get): net/minecraft/world/level/block/RenderShape.field_11455");
    }
    public static void m0051StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0051 (static set): net/minecraft/world/level/block/RenderShape.field_11455");
    }
    // TODO: implement the m0051 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/ChunkStatus.field_12798 (Lnet/minecraft/world/level/chunk/ChunkStatus;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.chunk.ChunkStatus. */
    public static Object m0052(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0052: net/minecraft/world/level/chunk/ChunkStatus.field_12798");
    }
    public static void m0052Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0052 (set): net/minecraft/world/level/chunk/ChunkStatus.field_12798");
    }
    public static Object m0052StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0052 (static get): net/minecraft/world/level/chunk/ChunkStatus.field_12798");
    }
    public static void m0052StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0052 (static set): net/minecraft/world/level/chunk/ChunkStatus.field_12798");
    }
    // TODO: implement the m0052 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/ChunkStatus.field_12803 (Lnet/minecraft/world/level/chunk/ChunkStatus;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.chunk.ChunkStatus. */
    public static Object m0053(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0053: net/minecraft/world/level/chunk/ChunkStatus.field_12803");
    }
    public static void m0053Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0053 (set): net/minecraft/world/level/chunk/ChunkStatus.field_12803");
    }
    public static Object m0053StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0053 (static get): net/minecraft/world/level/chunk/ChunkStatus.field_12803");
    }
    public static void m0053StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0053 (static set): net/minecraft/world/level/chunk/ChunkStatus.field_12803");
    }
    // TODO: implement the m0053 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118 (Lnet/minecraft/util/BitStorage;), which 1.20.1 does not have.
     *  Type: net.minecraft.util.BitStorage. */
    public static Object m0054(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0054: net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118");
    }
    public static void m0054Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0054 (set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118");
    }
    public static Object m0054StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0054 (static get): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118");
    }
    public static void m0054StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0054 (static set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_118");
    }
    // TODO: implement the m0054 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119 (Lnet/minecraft/world/level/chunk/Palette;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.chunk.Palette. */
    public static Object m0055(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0055: net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119");
    }
    public static void m0055Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0055 (set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119");
    }
    public static Object m0055StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0055 (static get): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119");
    }
    public static void m0055StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0055 (static set): net/minecraft/world/level/chunk/PalettedContainer$Data.comp_119");
    }
    // TODO: implement the m0055 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/chunk/PalettedContainer.field_34560 (Lnet/minecraft/world/level/chunk/PalettedContainer$Data;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.chunk.PalettedContainer$Data. */
    public static Object m0056(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0056: net/minecraft/world/level/chunk/PalettedContainer.field_34560");
    }
    public static void m0056Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0056 (set): net/minecraft/world/level/chunk/PalettedContainer.field_34560");
    }
    public static Object m0056StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0056 (static get): net/minecraft/world/level/chunk/PalettedContainer.field_34560");
    }
    public static void m0056StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0056 (static set): net/minecraft/world/level/chunk/PalettedContainer.field_34560");
    }
    // TODO: implement the m0056 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726 (Lnet/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType;), which 1.20.1 does not have.
     *  Type: net.minecraft.world.level.lighting.LayerLightSectionStorage$SectionType. */
    public static Object m0057(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0057: net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726");
    }
    public static void m0057Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0057 (set): net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726");
    }
    public static Object m0057StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0057 (static get): net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726");
    }
    public static void m0057StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0057 (static set): net/minecraft/world/level/lighting/LayerLightSectionStorage$SectionType.field_44726");
    }
    // TODO: implement the m0057 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1350D (), which 1.20.1 does not have.
     *  Type: . */
    public static Object m0058(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0058: net/minecraft/world/phys/Vec3.field_1350D");
    }
    public static void m0058Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0058 (set): net/minecraft/world/phys/Vec3.field_1350D");
    }
    public static Object m0058StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0058 (static get): net/minecraft/world/phys/Vec3.field_1350D");
    }
    public static void m0058StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0058 (static set): net/minecraft/world/phys/Vec3.field_1350D");
    }
    // TODO: implement the m0058 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1351D (), which 1.20.1 does not have.
     *  Type: . */
    public static Object m0059(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0059: net/minecraft/world/phys/Vec3.field_1351D");
    }
    public static void m0059Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0059 (set): net/minecraft/world/phys/Vec3.field_1351D");
    }
    public static Object m0059StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0059 (static get): net/minecraft/world/phys/Vec3.field_1351D");
    }
    public static void m0059StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0059 (static set): net/minecraft/world/phys/Vec3.field_1351D");
    }
    // TODO: implement the m0059 accessors against the 1.20.1 API
    /** Voxy reads net/minecraft/world/phys/Vec3.field_1352D (), which 1.20.1 does not have.
     *  Type: . */
    public static Object m0060(Object self) {
        throw new UnsupportedOperationException("RoxyForge bridge m0060: net/minecraft/world/phys/Vec3.field_1352D");
    }
    public static void m0060Set(Object self, Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0060 (set): net/minecraft/world/phys/Vec3.field_1352D");
    }
    public static Object m0060StaticGet() {
        throw new UnsupportedOperationException("RoxyForge bridge m0060 (static get): net/minecraft/world/phys/Vec3.field_1352D");
    }
    public static void m0060StaticSet(Object value) {
        throw new UnsupportedOperationException("RoxyForge bridge m0060 (static set): net/minecraft/world/phys/Vec3.field_1352D");
    }
    // TODO: implement the m0060 accessors against the 1.20.1 API
}
