package net.minecraft;

/**
 * RoxyForge shim for net/minecraft/class_11632, which exists in Minecraft 1.21 but not in 1.20.1.
 *
 * Generated by tools/roxy-mappings/make_shims.py from the unresolved references the link
 * checker found in Voxy. Only the surface Voxy actually touches is declared. Bodies are
 * placeholders: this gets Voxy's bytecode to link, and the game run is what shows which
 * of these calls need real implementations.
 */
public class class_11632 {
}
